// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeraAPI.Models;

#nullable disable

namespace PrimeraAPI.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20251020193707_nuevo curso")]
    partial class nuevocurso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrimeraAPI.Models.Clases", b =>
                {
                    b.Property<int>("Id_Clase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Clase"));

                    b.Property<string>("Autor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Id_Profe")
                        .HasColumnType("int");

                    b.Property<string>("ImagenClase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tema")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Clase");

                    b.ToTable("Clases");
                });

            modelBuilder.Entity("PrimeraAPI.Models.Cursos", b =>
                {
                    b.Property<int>("Id_curso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_curso"));

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<int>("Id_user")
                        .HasColumnType("int");

                    b.Property<string>("Json_string")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Num_sections")
                        .HasColumnType("int");

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.HasKey("Id_curso");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("PrimeraAPI.Models.Estudi_Clases", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Id_Clase")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Usuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Estudi_Clases");
                });

            modelBuilder.Entity("PrimeraAPI.Models.Estudi_Examen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Aciertos")
                        .HasColumnType("int");

                    b.Property<int?>("Fallos")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Estudiane")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Examen")
                        .HasColumnType("int");

                    b.Property<int?>("Intentos")
                        .HasColumnType("int");

                    b.Property<float?>("Nota")
                        .HasColumnType("real");

                    b.Property<string>("Recomendacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estudi_Examenes");
                });

            modelBuilder.Entity("PrimeraAPI.Models.Examenes", b =>
                {
                    b.Property<int>("Id_Examen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Examen"));

                    b.Property<string>("Autor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Id_Clase")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Juego")
                        .HasColumnType("int");

                    b.Property<string>("ImagenExamen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tema")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Examen");

                    b.ToTable("Examenes");
                });

            modelBuilder.Entity("PrimeraAPI.Models.Juego_Examen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo_Exa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_Juego")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Juegos_Examenes");
                });

            modelBuilder.Entity("PrimeraAPI.Models.Juegos", b =>
                {
                    b.Property<int>("Id_Juego")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Juego"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Juego");

                    b.ToTable("Juegos");
                });

            modelBuilder.Entity("PrimeraAPI.Models.Palabras_Ahorcado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo_Exa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Palabra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pista")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Palabras_Ahorcados");
                });

            modelBuilder.Entity("PrimeraAPI.Models.Preguntas_Heroes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo_Exa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pregunta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespuestaF1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespuestaF2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespuestaF3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespuestaV")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Preguntas_Heroes");
                });

            modelBuilder.Entity("PrimeraAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<string>("Contrasena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
